### ISSUE TITLE
怎么开启自动下载专辑和艺术家封面？

### ISSUE THREAD

**Issue by Yaseen1314** [TooAndy/navichina#2]
![image](https://github.com/user-attachments/assets/42897976-9da2-471d-bd4e-83412b8e8507)

**Comment by TooAndy** [comment]
在 docker compose文件中添加两行环境变量
```yaml
      - COVER_AUTO_DOWNLOAD=true
      - ALBUM_REGEX_PATTERN=\d+--(.+)
```
`ALBUM_REGEX_PATTERN`这个正则表达式是为了匹配专辑名称, 我自己的音乐全都使用如下格式整理的:
```shell
周杰伦
├── 2000--Jay
│   ├── 01.可爱女人.flac
│   ├── 01.可爱女人.lrc
│   ├── 02.完美主义.flac
│   ├── 02.完美主义.lrc
│   ├── 03.星晴.flac
│   ├── 03.星晴.lrc
│   ├── ......
│   ├── ......
│   ├── cover.jpg
│   └── Thumbs.db
├── 2001--Fantasy Plus
│   ├── 01.蜗牛.flac
│   ├── 01.蜗牛.lrc
│   ├── 02.你比从前快乐.flac
│   ├── 02.你比从前快乐.lrc
│   ├── 03.世界末日.flac
│   ├── 03.世界末日.lrc
│   ├── cover.jpg
│   └── Thumbs.db

```
因此我这边填写的`ALBUM_REGEX_PATTERN`为`\d+--(.+)`, 只把括号中匹配的当成专辑名.

如果你的专辑名前面没有年份, 就是`Jay` `范特西`之类的, 那可以不填, 默认是 `(.*)`

PS: 可以看一下`cover.py`

完整`compose.yaml`如下
```yaml
services:
  navidrome:
    container_name: navidrome
    image: tooandy/navidrome:latest
    user: 0:0  # 需要对卷有写入权限
    network_mode: host
    restart: unless-stopped
    environment:
      - ND_CONFIGFILE=/data/navidrome.toml
    volumes:
      - /root/.config/navidrome:/data
      - /path/to/your/music:/music
    depends_on:
      - navichina

  navichina:
    container_name: navichina
    image: tooandy/navichina:latest
    user: 0:0   # 需要对卷有写入权限.
    restart: unless-stopped
    volumes:
      - /tmp/.cache:/.cache
      - /path/to/your/music:/music  # 如果需要 navidrome 将艺术家和专辑封面下载到音乐路径中, 需要和 navidrome 的卷设置相同.
    ports:
      - 22522:22522   # 外部端口需要设置为 22522, 因为 tooandy/navidrome 容器默认访问 22522 端口. 如果需要修改端口, 建议石笋 navichina 项目中的 build-navidrome.sh 脚本重新构建一个镜像
    environment:
      - COVER_AUTO_DOWNLOAD=true
      - ALBUM_REGEX_PATTERN=\d+--(.+)    # 说明我本地专辑对应的文件夹命名格式为`2001--Jay`, 其中`Jay` 为真正的专辑名, 程序根据这个`Jay`搜索专辑封面 
```
